# shellcheck shell=bash
# lib/keys.sh — Single source of truth for launch.d config key names.
#
# Sourced after lib/common.sh. Used by config reset, summaries, and validation.

[[ -n "${LAUNCHLAYER_KEYS_LOADED:-}" ]] && return 0
LAUNCHLAYER_KEYS_LOADED=1

# Keys exported from .env layers and cleared by reset_config_state.
LAUNCHLAYER_CONFIG_KEYS=(
	BENCHMARK GAMEMODE MANGOHUD MANGOHUD_LOG MANGOHUD_CONFIG MANGOHUD_CONFIGFILE
	NETWORK_TUNE DEBUG X3D_CPUS GAME_NIC GAMESCOPE GAMESCOPE_W GAMESCOPE_H GAMESCOPE_R
	GAMESCOPE_ADAPTIVE_SYNC GAMESCOPE_EXPOSE_WAYLAND GAMESCOPE_FSR GAMESCOPE_FSR_SHARPNESS
	SHADER_CACHE_CHECK SHADER_CACHE_MAX_GB SHADER_CACHE_TRIM SHADER_CACHE_CHECK_INTERVAL_HOURS
	COMPATDATA_CHECK COMPATDATA_MAX_GB COMPATDATA_TRIM VM_MAX_MAP_COUNT_MIN VM_MAX_MAP_COUNT_FIX
	VRAM_HOG_UNITS VRAM_HOGS VRAM_HOG_PIDS LAUNCH_WATCHDOG LAUNCH_WRAPPERS LAUNCH_WRAPPERS_BEFORE
	GAME_EXTRA_ARGS UNSET_VARS FORCE_NATIVE FORCE_PROTON VRAM_PREFLIGHT_MIN_MB
	PIPEWIRE_LOW_LATENCY LAUNCH_LOG_MAX_LINES PRE_LAUNCH_CMD POST_LAUNCH_CMD
	DISK_PREFLIGHT_MIN_GB GPU_POWER_CHECK NVIDIA_POWER_MODE CONCURRENT_LAUNCH_GUARD GPU_VRAM_PROCESS_MIN_MB
	DISABLE_CPU_AFFINITY GAME_PERFORMANCE
)

# Subset shown in --show-config summaries and JSON settings output.
LAUNCHLAYER_SUMMARY_KEYS=(
	INCLUDE BENCHMARK GAMEMODE MANGOHUD GAMESCOPE VRAM_HOGS NETWORK_TUNE PIPEWIRE_LOW_LATENCY
	LAUNCH_WRAPPERS LAUNCH_WRAPPERS_BEFORE GAME_EXTRA_ARGS UNSET_VARS FORCE_NATIVE FORCE_PROTON
	X3D_CPUS GAMESCOPE_W GAMESCOPE_H GAMESCOPE_R SHADER_CACHE_TRIM VRAM_PREFLIGHT_MIN_MB
	GPU_POWER_CHECK DISK_PREFLIGHT_MIN_GB PRE_LAUNCH_CMD POST_LAUNCH_CMD NVIDIA_POWER_MODE
	DISABLE_CPU_AFFINITY GAME_PERFORMANCE
)

# known_config_key — Return 0 if key is a recognized launch.d setting.
known_config_key() {
	local key=$1 k
	[[ "$key" == INCLUDE ]] && return 0
	for k in "${LAUNCHLAYER_CONFIG_KEYS[@]}"; do
		[[ "$key" == "$k" ]] && return 0
	done
	case "$key" in
		PROTON_*|DXVK_*|VKD3D_*|__GL_*|__VK_*|WINE*|STEAM_*) return 0 ;;
	esac
	return 1
}
