# shellcheck shell=bash
# lib/keys.sh — Single source of truth for launch.d config key names.
#
# Sourced after lib/common.sh. Used by config reset, summaries, and validation.

[[ -n "${LAUNCHLAYER_KEYS_LOADED:-}" ]] && return 0
LAUNCHLAYER_KEYS_LOADED=1

# Keys exported from .env layers and cleared by reset_config_state.
LAUNCHLAYER_CONFIG_KEYS=(
	BENCHMARK GAMEMODE MANGOHUD MANGOHUD_LOG MANGOHUD_CONFIG MANGOHUD_CONFIGFILE
	NETWORK_TUNE DEBUG X3D_CPUS GAME_NIC GAMESCOPE GAMESCOPE_W GAMESCOPE_H GAMESCOPE_R
	GAMESCOPE_ADAPTIVE_SYNC GAMESCOPE_EXPOSE_WAYLAND GAMESCOPE_FSR GAMESCOPE_FSR_SHARPNESS
	GAMESCOPE_EXTRA_ARGS GAMESCOPE_PREFER_OUTPUT GAMESCOPE_FRAME_LIMIT GAMESCOPE_FILTER
	GAMESCOPE_FOCUSED_FPS GAMESCOPE_UNFOCUSED_FPS GAMESCOPE_NESTED_FIX
	SHADER_CACHE_CHECK SHADER_CACHE_MAX_GB SHADER_CACHE_TRIM SHADER_CACHE_CHECK_INTERVAL_HOURS
	SHADER_CACHE_BOOST SHADER_CACHE_BOOST_GB
	COMPATDATA_CHECK COMPATDATA_MAX_GB COMPATDATA_TRIM VM_MAX_MAP_COUNT_MIN VM_MAX_MAP_COUNT_FIX
	VRAM_HOG_UNITS VRAM_HOGS VRAM_HOG_PIDS LAUNCH_WATCHDOG LAUNCH_WRAPPERS LAUNCH_WRAPPERS_BEFORE
	GAME_EXTRA_ARGS UNSET_VARS FORCE_NATIVE FORCE_PROTON VRAM_PREFLIGHT_MIN_MB
	PIPEWIRE_LOW_LATENCY LAUNCH_LOG_MAX_LINES PRE_LAUNCH_CMD POST_LAUNCH_CMD
	DISK_PREFLIGHT_MIN_GB GPU_POWER_CHECK NVIDIA_POWER_MODE CONCURRENT_LAUNCH_GUARD GPU_VRAM_PROCESS_MIN_MB
	DISABLE_CPU_AFFINITY GAME_PERFORMANCE CPU_AFFINITY_RANGE DISABLE_NIC_EEE DISABLE_WIFI_POWER_SAVE
	MALLOC_ALLOCATOR ENABLE_HDR GAMESCOPE_HDR DISK_TUNE OVERRIDE_PROTON DLSS_SWAPPER
	PROTON_DLSS_UPGRADE PROTON_DLSS_INDICATOR PROTON_FSR4_UPGRADE PROTON_FSR4_RDNA3_UPGRADE
	PROTON_FSR4_INDICATOR PROTON_XESS_UPGRADE PROTON_NVIDIA_LIBS PROTON_NVIDIA_LIBS_NO_32BIT
	LD_BIND_NOW VKBASALT VKBASALT_CONFIG_FILE VKBASALT_LOG_LEVEL LATENCYFLEX DISABLE_VBLANK
	DISABLE_STEAM_DECK FRAME_RATE
	LSFG_VK LSFG_PROCESS LSFG_CONFIG_FILE
	OBS_VKCAPTURE DISCORD_IPC REPLAY_CAPTURE REPLAY_TOOL BLOCK_INTERNET CONTY CONTY_PATH
	WINETRICKS_VERBS WINETRICKS_GUI WINECFG_BEFORE REGISTRY_FILES WINE_FSR WINE_FSR_STRENGTH WINE_FSR_MODE
	SPECIAL_K SPECIAL_K_DLL SPECIAL_K_SOURCE SPECIAL_K_INI SPECIAL_K_FETCH SPECIAL_K_FETCH_URL SPECIAL_K_VERSION
	RESHADE RESHADE_DLL RESHADE_SOURCE RESHADE_SK_VERSION DEPTH3D DEPTH3D_SOURCE DEPTH3D_FETCH_URL
	SKIF SKIF_PATH SKIF_LAUNCH VALVEPLUG VALVEPLUG_SOURCE VALVEPLUG_STEAM_DIR
	FLAWLESS_WIDESCREEN FWS FWS_PATH FWS_COLAUNCH
	SPECIALTY_RUNTIME OPENVR_FSR OPENVR_FSR_SOURCE GEO11 GEO11_SOURCE GEO11_SBS_VR
	SBS_VR SBS_VR_PLAYER SBS_VR_REQUIRE_HMD FLAT2VR FLAT2VR_SOURCE
	PLAYTIME_LOG CRASH_GUESS CRASH_GUESS_TIMEOUT
	INJECT_SHA256
)

# Subset shown in --show-config summaries and JSON settings output.
LAUNCHLAYER_SUMMARY_KEYS=(
	INCLUDE BENCHMARK GAMEMODE MANGOHUD GAMESCOPE VRAM_HOGS NETWORK_TUNE PIPEWIRE_LOW_LATENCY
	LAUNCH_WRAPPERS LAUNCH_WRAPPERS_BEFORE GAME_EXTRA_ARGS UNSET_VARS FORCE_NATIVE FORCE_PROTON
	X3D_CPUS GAMESCOPE_W GAMESCOPE_H GAMESCOPE_R SHADER_CACHE_TRIM VRAM_PREFLIGHT_MIN_MB
	GPU_POWER_CHECK DISK_PREFLIGHT_MIN_GB PRE_LAUNCH_CMD POST_LAUNCH_CMD NVIDIA_POWER_MODE
	DISABLE_CPU_AFFINITY GAME_PERFORMANCE CPU_AFFINITY_RANGE DISABLE_NIC_EEE DISABLE_WIFI_POWER_SAVE
	MALLOC_ALLOCATOR ENABLE_HDR GAMESCOPE_HDR DISK_TUNE OVERRIDE_PROTON DLSS_SWAPPER
	SHADER_CACHE_BOOST PROTON_DLSS_UPGRADE PROTON_FSR4_UPGRADE PROTON_XESS_UPGRADE
	LD_BIND_NOW VKBASALT LATENCYFLEX DISABLE_VBLANK
	DISABLE_STEAM_DECK FRAME_RATE
	LSFG_VK OBS_VKCAPTURE DISCORD_IPC REPLAY_CAPTURE BLOCK_INTERNET CONTY
	SPECIAL_K RESHADE DEPTH3D WINETRICKS_VERBS FLAWLESS_WIDESCREEN SPECIALTY_RUNTIME
	OPENVR_FSR GEO11 SBS_VR FLAT2VR PLAYTIME_LOG
)

# known_config_key — Return 0 if key is a recognized launch.d setting.
known_config_key() {
	local key=$1 k
	[[ "$key" == INCLUDE ]] && return 0
	for k in "${LAUNCHLAYER_CONFIG_KEYS[@]}"; do
		[[ "$key" == "$k" ]] && return 0
	done
	case "$key" in
		PROTON_*|DXVK_*|VKD3D_*|__GL_*|__VK_*|WINE*|STEAM_*|SDL_*|MESA_*|mesa_*|RADV_*|AMD_*|INTEL_*) return 0 ;;
	esac
	return 1
}
